### ISSUE TITLE
Opaque to Transparent

### ISSUE THREAD

**Issue by glee38** [learn-co-curriculum/js-jquery-methods-readme#11]
This lab refers to an object gradually fading out or disappearing as "opaque", however, I think this may have been a mistake since opaque means that the object is not transparent, or not able to be seen through. Maybe it was supposed to say transparent?

<img width="908" alt="screen shot 2016-08-11 at 4 30 01 pm" src="https://cloud.githubusercontent.com/assets/15304564/17603858/08396706-5fe1-11e6-8391-38b4731d7300.png">

<img width="910" alt="screen shot 2016-08-11 at 4 30 16 pm" src="https://cloud.githubusercontent.com/assets/15304564/17603864/0fcd61ac-5fe1-11e6-9091-7e6e7d4dc0f6.png">

Wasn't sure if this was on purpose, or maybe I am misunderstanding it? If so, I apologize in advance!

**Comment by AnnJohn** [comment]
thanks for raising this. we changed the wording to be a bit more clear.
