### ISSUE TITLE
the specs aren't working properly

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/js-jquery-methods-readme#4]
@loganhasson reviewed this and it needs to be checked out

**Comment by AnnJohn** [comment]
duplicate issue, closing

**Comment by victhevenot** [comment]
definitely need more insight here @kvignali @loganhasson. solution specs all pass as expected...

**Comment by AnnJohn** [comment]
@pletcher can you look at this again and if specs are working, you can just go ahead and close. thanks.

**Comment by pletcher** [comment]
`learn-test` worked okay for me. Feel free to re-open if the issue persists.
